apiVersion: v1
entries:
  bnk-gateway:
  - created: 2025-10-10T09:23:27.499543808-06:00
    description: Create F5 BNK Gateway-api resource
    home: https://www.f5.com
    name: bnk-gateway
    sources:
    - https://github.com/stanislaspiron/k3s-bnk/
    urls:
    - https://raw.githubusercontent.com/stanislaspiron/k3s-bnk/refs/heads/main/charts/bnk-gateway-0.1.0.tgz
    version: 0.1.1
  - created: 2025-10-10T09:23:27.499543808-06:00
    description: Create F5 BNK Gateway-api resource
    home: https://www.f5.com
    name: bnk-gateway
    sources:
    - https://github.com/stanislaspiron/k3s-bnk/
    urls:
    - https://raw.githubusercontent.com/stanislaspiron/k3s-bnk/refs/heads/main/charts/bnk-gateway-0.2.0.tgz
    version: 0.2.0
  - created: 2025-10-10T09:23:27.499543808-06:00
    description: Create F5 BNK Gateway-api resource
    home: https://www.f5.com
    name: bnk-gateway
    sources:
    - https://github.com/stanislaspiron/k3s-bnk/
    urls:
    - https://raw.githubusercontent.com/stanislaspiron/k3s-bnk/refs/heads/main/charts/bnk-gateway-0.2.3.tgz
    version: 0.2.3
  - created: 2025-10-10T09:23:27.499543808-06:00
    description: Create F5 BNK Gateway-api resource
    home: https://www.f5.com
    name: bnk-gateway
    sources:
    - https://github.com/stanislaspiron/k3s-bnk/
    urls:
    - https://raw.githubusercontent.com/stanislaspiron/k3s-bnk/refs/heads/main/charts/bnk-gateway-0.2.4.tgz
    version: 0.2.4
  - created: 2025-10-10T09:23:27.499543808-06:00
    description: Create F5 BNK Gateway-api resource
    home: https://www.f5.com
    name: bnk-gateway
    sources:
    - https://github.com/stanislaspiron/k3s-bnk/
    urls:
    - https://raw.githubusercontent.com/stanislaspiron/k3s-bnk/refs/heads/main/charts/bnk-gateway-0.2.6.tgz
    version: 0.2.6