{{- if (.Values.gateway).enabled }}
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ .Values.gateway.name | quote }}
  labels:
    kubernetes.io/service-name: {{ .Values.gateway.name | quote }}
addressType: IPv4
ports: []
#  - name: fake-service
#    protocol: TCP
#    port: 8080
endpoints:
  - addresses:
    {{- range .Values.gateway.addresses }}
    - {{ . | quote }}
    {{- end }}
{{- end }}