{{- if (.Values.httpRoute).enabled -}}
{{- range .Values.httpRoute.items }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .name | quote }}
  {{- with .annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .parentRefs }}
  parentRefs:
  {{- toYaml . | nindent 4 -}}
  {{- end }}
  {{- with .hostnames }}
  hostnames:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  {{- with .rules }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}