{{- if (.Values.egress).isolation }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ns-isolation-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}  # Apply to all pods in namespace
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector: {}  # Allow all pods in the same namespace
    - from:
      {{- range .Values.egress.tmm_addresses }}
      - ipBlock:
          cidr: {{. | quote }}  # allow ingress from TMM internal self IP
      {{- end }}
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0  # allow egress to external IPs
{{- end }}